# Generated by Django 5.2.3 on 2025-06-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verificationrequest",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verificationrequest",
            name="student_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verificationrequest",
            name="verification_document",
            field=models.FileField(
                blank=True, null=True, upload_to="verification_documents/"
            ),
        ),
    ]
